services:
            
    Sintra\TrainingBundle\Command\BackgroundProcessesCommand:
        arguments:
            - '@process_manager.factory.process'
            - '@process_manager.logger'
        tags:
            - { name: 'console.command', command: 'sintra-training:background-process' }
